# SPDX-License-Identifier: GPL-2.0-only
# Out-of-tree modules for the ATK-DLRK3588. Rust modules use the kernel
# crate APIs added by ../patches; the panel uses the upstream DRM API;
# build them with make -C <kernel> O=<build> M=$(pwd) MO=<out> modules.
obj-m += rust_dw_uart.o
obj-m += rust_chardev.o
obj-m += panel-alientek-md0550.o
